repos:
    - repo: https://github.com/psf/black
      rev: 21.9b0
      hooks:
          - id: black
            language_version: python3.8
    - repo: https://github.com/timothycrosley/isort
      rev: 5.9.3
      hooks:
          - id: isort
    - repo: https://gitlab.com/pycqa/flake8.git
      rev: 3.9.2
      hooks:
          - id: flake8
            files: ^(src/|app/)
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.782
      hooks:
          - id: mypy
            files: ^(src/|app/)
    - repo: https://github.com/pycqa/pydocstyle
      rev: 5.0.2
      hooks:
          - id: pydocstyle
            files: ^(src/|app/)
            exclude: (test_.*|__init__)\.py
            args: [--convention=google]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-merge-conflict
          - id: debug-statements
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]
